scriptManager:
    databaseFile: epadata.sqlite
    loaderScript: loader.py

httpManager:
    enabled: true
    port: 36000
    whitelist: false
    authentication: false
    addresses:
      -  127.0.0.1
    users:
        admin: admin